### PR TITLE
Added a failing test in IMP/em

### PR DESCRIPTION
**Pull request by shanot**
related to issue  #948

sample output :

```
======================================================================
ERROR: Test creation DensityMap from grid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_rasterization.py", line 34, in test_rasterization
    d_slow=IMP.em.create_density_map(grid_slow)
  File "/work/sam/imp_sam-fast/lib/IMP/em/__init__.py", line 994, in create_density_map
    return _IMP_em.create_density_map(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'create_density_map'.
  Possible C/C++ prototypes are:
    IMP::em::create_density_map(IMP::em::DensityMap const *)
    IMP::em::create_density_map(IMP::algebra::BoundingBox3D const &,double)
    IMP::em::create_density_map(int,int,int,double)
    IMP::em::create_density_map(IMP::algebra::GridD< 3,IMP::algebra::DenseGridStorageD< 3,float >,float,IMP::algebra::DefaultEmbeddingD< 3 > > const &)
    IMP::em::create_density_map(IMP::algebra::GridD< 3,IMP::algebra::DenseGridStorageD< 3,double >,double,IMP::algebra::DefaultEmbeddingD< 3 > > const &)


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

### CODE REVIEW

**Comment by cgreenberg** [comment]
This test passes for me. Did you rebuild recently?

**Comment by shanot** [comment]
I cloned a fresh copy this morning, built it as usual

```
#!/bin/bash
module load boost/1.54.0-python-2.7.5-shared
module load python/2.7.5-shared
module load gcc/4.6.2-gmp-4.3.2-mpfr-3.1.0-mpc-0.8.2
module load swig/2.0.4
module load cmake/3.0.2
module load ninja/1.3.4
module load git/1.8.2.1
module load hdf5/1.8.10
module load openmpi/1.6.3/gcc-4.6.2-gmp-4.3.2-mpfr-3.1.0-mpc-0.8.2--disable-dlopen



cmake \
	../imp_sam/ \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DIMP_MAX_LOG=SILENT \
  -DIMP_MAX_CHECKS=NONE  \
  -DCMAKE_CXX_COMPILER=/c5/shared/openmpi/1.6.3/sge/6.2u4/gcc-4.6.2-gmp-4.3.2-mpfr-3.1.0-mpc-0.8.2--disable-dlopen/bin/mpicxx \
  -DCMAKE_C_COMPILER=/c5/shared/openmpi/1.6.3/sge/6.2u4/gcc-4.6.2-gmp-4.3.2-mpfr-3.1.0-mpc-0.8.2--disable-dlopen/bin/mpicc \
  -DCMAKE_INCLUDE_PATH=/c5/shared/Python/2.7.5-shared/include \
  -DCMAKE_LIBRARY_PATH=/c5/shared/Python/2.7.5-shared/lib \
  -DHDF5_INCLUDE_DIR=/c5/shared/hdf5/1.8.10/include/ \
  -DBOOST_ROOT=/c5/shared/boost/1.54.0/python-2.7.5-shared/

ninja
```

and I get the error above...

**Comment by shanot** [comment]
Identical result on my laptop running archlinux. I built imp from the source at commit 5a4862413427376be3b21ab4ccdf2e3a31167c5b.

**Comment by Pellarin** [comment]
The test passes on my MacOS laptop but not on my Linuxbox. Can someone help us with this issue? @benmwebb ? @cgreenberg ?

**Comment by Pellarin** [comment]
Changing `typedef DenseGrid3D<double> DensityGrid` to `typedef DenseGrid3D<float> DensityGrid` does the work. I think it might be a compiler problem. 

See the patch below:

```
diff --git a/modules/algebra/include/Gaussian3D.h b/modules/algebra/include/Gaussian3D.h
index 42e2b8d..a1ffb47 100644
--- a/modules/algebra/include/Gaussian3D.h
+++ b/modules/algebra/include/Gaussian3D.h
@@ -18,7 +18,7 @@
 
 IMPALGEBRA_BEGIN_NAMESPACE
 
-typedef DenseGrid3D<double> DensityGrid;
+typedef DenseGrid3D<float> DensityGrid;
 //! A Gaussian distribution in 3D.
 /** The variances are along the axis of the reference frame.
 */
```

**Comment by shanot** [comment]
FYI running in debug yields no additional information.

**Comment by cgreenberg** [comment]
I'll accept the test and maybe we can figure out what's going on.

**Comment by shanot** [comment]
I tried a variety of compilers (clang, gcc) in addition to mpicc, on multiple linux boxes and I always get that issue.

**Comment by benmwebb** [comment]
We possibly don't see this because we build with checks turned on and your test fails earlier because it hits a failed check, e.g. [on RH 6](http://integrativemodeling.org/nightly/logs/develop/20160602/pkg.el6-x86_64/em.test.log). (It looks like that's the code from your previous PR, so either a bug in that code or in the check.) Fix that and then we'll see whether we get the same issue. But we test on a pretty wide range of platforms with fresh builds, and we're definitely not seeing the issue you're reporting on any of them.

That said, it's possible you're running into a subtle problem, but we can't help you unless we can reproduce it. That means you'll need to reproduce it on a standard version of Linux that we can also get hold of, with standard system packages (obviously we don't have your custom packages in `/c5/shared`). At that point we can reproduce your setup more or less exactly in a VM or Docker container.

**Comment by Pellarin** [comment]
Given what @benmwebb says, 

```
UsageException: Usage check failure: Using uninitialized grid index
```

is an exception of `GridIndex`

@shanot maybe the check fails at 
```
GridIndex3D i(voxel_index[0], voxel_index[1], voxel_index[2]);
```
in `get_rasterized_fast`

**Comment by Pellarin** [comment]
I fixed the issue using the following patch:

```
diff --git a/modules/algebra/include/Gaussian3D.h b/modules/algebra/include/Gaussian3D.h
index 42e2b8d..a1493b0 100644
--- a/modules/algebra/include/Gaussian3D.h
+++ b/modules/algebra/include/Gaussian3D.h
@@ -18,7 +18,7 @@
 
 IMPALGEBRA_BEGIN_NAMESPACE
 
-typedef DenseGrid3D<double> DensityGrid;
+typedef IMP::algebra::GridD< 3,IMP::algebra::DenseGridStorageD< 3,double >,double,IMP::algebra::DefaultEmbeddingD< 3 > > DensityGrid;
 //! A Gaussian distribution in 3D.
 /** The variances are along the axis of the reference frame.
 */
```

Would it be possible to have this patch applied in the main code?

**Comment by benmwebb** [comment]
As I said before, we can't "fix" an issue without being able to reproduce it first... did you try it on a standard version of Linux?

**Comment by Pellarin** [comment]
Here we have the linux boxes and the mac laptops. The original version seemed to work fine on the mac laptop but not on the linux boxes (any of them). We got the solution that is described in the patch, and it should be fine on all architectures, because it simply replaces another typedef. Yes, it's true, we still don't know why it does not work on our linux boxes...

**Comment by benmwebb** [comment]
Does your patch also work for @shanot? if so, since it seems to be essentially only a syntactic change, I'd be OK with merging it. Open a pull request. (You should probably add a comment though explaining why we don't use the much simpler `DenseGrid3D` class.)

**Pull request merged**
